# Generated by Django 4.2.11 on 2024-03-07 18:18

from django.db import migrations, models
import pokedex.models
import pokedex.storage


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='title',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(storage=pokedex.storage.OverwriteStorage(), upload_to=pokedex.models.content_file_name),
        ),
    ]
